config/routes.rb
Rails.application.routes.draw do
  resources :investments
  root to: 'home#index'
  get 'sessions/new'

  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
  has_many :investments
  include ::Price

  def url
    source
  end
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :investments
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
  belongs_to :cryptocurrency
  belongs_to :currency
  belongs_to :market

  delegate :current_price,
    to: :cryptocurrency

  def actual_value
    @actual_value =|| ::CurrentValue.for(current_price, coins, price)
  end

  def currency_name
    currency.name
  end

  def cryptocurrency_name
    cryptocurrency.name
  end

  def profit
    @profit =|| Profit.new(actual_value, price)
  end

  def market_name
    market_type = market || UnknonwMarket.new.name

    market_type.name
  end

  def current_sell_price
    current_price * coins
  end

  def profit_percentage
    profit.percentage
  end
end

app/models/market.rb
class Market < ApplicationRecord
end

app/models/profit.rb
class Profit
  attr_reader :actual_value, :price

  def initialize(actual_value, price)
    @actual_value, @price = actual_value, price 
  end
  
  def percentage
    (actual_value / price) * 100
  end
end

app/models/unknonw_market.rb
class UnknonwMarket
  def name
    'unknonw'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :investments

  def profit
    investments.map(&:actual_value).sum.round(2)
  end

  def balance_in_euro
    (investments.map(&:price).sum + profit).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def logged_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: [:show, :edit, :update, :destroy]

  # GET /investments
  # GET /investments.json
  def index
    @investments = current_user.investments.all
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = current_user.investments.build(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment.destroy
    respond_to do |format|
      format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = current_user.investments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.require(:investment).permit(:currency_id, :price, :coins, :date, :market_id, :cryptocurrency_id)
    end

    def redirect_to_login
      redirect_to root_url
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)
    if @user.save
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  private

  def allowed_params
    params.require(:user).permit(:email, :password, :password_confirmation, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/investments/_form.html.slim
= form_with(model: investment, local: true) do |form|
  - if investment.errors.any?
    #error_explanation
      h2
        = pluralize(investment.errors.count, "error")
        | prohibited this investment from being saved:
      ul
        - investment.errors.full_messages.each do |message|
          li= message
  .form-group
    = form.label :currency
    br/
    = form.select(:currency_id, Currency.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Currency'})
  .form-group
    = form.label :cryptocurrency
    br/
    = form.select(:cryptocurrency_id, Cryptocurrency.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Cryptourrency'})
  .form-group
    = form.label :total_paid
    br/
    = form.text_field :price, id: :investment_price, type: :number, step: :any
    p.form-text.text-muted
      | How much did you pay these coins including the fees?
  .form-group
    = form.label :coins
    br/
    = form.text_field :coins, id: :investment_coins, type: :number, step: :any
    p.form-text.text-muted
      | How many coins have been transfered with this transaction into your cryptowallet?
  .form-group
    = form.label :date
    br/
    = form.datetime_select :date, id: :investment_date
    p.form-text.text-muted
      | When did you buy the coins?
  .form-group
    = form.label :market_id
    br/
    = form.select(:market_id, Market.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Market'})
    p.form-text.text-muted
      | Where did you buy the coins?
  .form-group
    = form.submit "Create", class: 'btn btn-default'

app/views/investments/edit.html.erb
<h1>Editing Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.slim
p#notice= notice
/! <h1>Investments</h1
table.table.table-responsive
  thead
    tr
      th Currency
      th Price Paid
      th Current Sell Price
      th Profit %
      th Current Price
      th Coins
      th Date
      th Market
      th Profit

      th
      th colspan="3"
  tbody
    - @investments.each do |investment|
      tr
        td= investment.cryptocurrency_name
        td= investment.price.round(2)
        td= investment.current_sell_price.round(2)
        td= investment.profit_percentage.round
        td= investment.current_price.round(2)
        td= investment.coins
        td= investment.date
        td= investment.market_name
        td= investment.actual_value.round(5)
        td= link_to 'Show', investment
        td= link_to 'Edit', edit_investment_path(investment)
        td= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' }

hr/
h4
  = "Total #{@current_user.profit}"
h4
  = "Total balance in euro #{@current_user.balance_in_euro}"
br/
center
  btn.btn-default
    = link_to 'New Investment', new_investment_path
br/

app/views/investments/new.html.erb
<h1>Record a new investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Currency:</strong>
  <%= @investment.currency_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @investment.price %>
</p>

<p>
  <strong>Coins:</strong>
  <%= @investment.coins %>
</p>

<p>
  <strong>Date:</strong>
  <%= @investment.date %>
</p>

<p>
  <strong>Market:</strong>
  <%= @investment.market_name %>
</p>

<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', investments_path %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /

    meta name="viewport" content="width=device-width, initial-scale=1" /
    title Portfolio
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
      .container
        a.navbar-brand href="/" Cryptomonitor
        button.navbar-toggler aria-controls="navbarResponsive" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarResponsive" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        #navbarResponsive.collapse.navbar-collapse
          ul.navbar-nav.ml-auto
            li.nav-item
              a.nav-link href="/" Home
            - if logged_in?
              li.nav-item
                = link_to 'Logout', session_path('logout'), method: :delete, class: 'nav-link'
              li.nav-item
                a.nav-link href="/investments"  Investments
            - else
              li.nav-item
                = link_to "Sign Up", new_user_path, class: 'nav-link'
              li.nav-item
                = link_to "Log In", new_session_path, class: 'nav-link'

    .template
      .container
        #user_header
        = yield

app/views/users/new.html.slim
h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      h2 Form is invalid
      ul
        - @user.errors.full_messages.each do |message|
          li= message
  .form-group
    = f.label :email
    br/
    = f.text_field :email, type: :email
  .form-group
    = f.label :password
    br/
    = f.password_field :password
  .form-group
    = f.label :password_confirmation
    br/
    = f.password_field :password_confirmation
  = f.submit "Sign Up", class: 'btn btn-default'